--- ocp.toml.orig	2021-05-24 10:47:30 UTC
+++ ocp.toml
@@ -361,6 +361,10 @@ parsing_header = '''#pragma clang diagnostic ignored "
     modules = ["Xw"]
     symbols = "symbols_mangled_linux.dat"
 
+[FreeBSD]
+    modules = ["Xw"]
+    symbols = "symbols_mangled_freebsd.dat"
+
 [Windows]
     modules = ["WNT"]
     exclude_classes = ["Handle_*"]
@@ -632,7 +636,8 @@ parsing_header = '''#pragma clang diagnostic ignored "
 struct NSOpenGLContext {};"""
         include_body_pre = 'py::class_<NSOpenGLContext>(m, "NSOpenGLContext");'
         exclude_methods = ["OpenGl_GlCore11::glGetPointerv","OpenGl_RaytraceGeometry::Clear",
-                           "OpenGl_View::ChangeGraduatedTrihedron","OpenGl_View::LayerList"]
+                           "OpenGl_View::ChangeGraduatedTrihedron","OpenGl_View::LayerList",
+                           "OpenGl_VertexBuffer::unbindFixedColor"]
         exclude_typedefs = ["OpenGl_SequenceOfLayers","OpenGl_SetterList","OpenGl_MapOfHatchStylesAndIds","OpenGl_MapOfZLayerSettings","OpenGl_IndexedMapOfStructure","OpenGl_MapOfShaderPrograms","OpenGl_IndexedMapOfStructure","OpenGl_LayerSeqIds"]
         exclude_classes = ["OpenGl_GraduatedTrihedron","OpenGl_LayerList","OpenGl_VariableSetterSelector","OpenGl_RaytraceGeometry"]
         
@@ -1089,4 +1094,4 @@ using rapidjson::BasicOStreamWrapper;"""
         
     [Modules.IVtkOCC]
 
-        exclude_methods = ["IVtkOCC_ShapePickerAlgo::Pick", "IVtkOCC_ViewerSelector::Pick"]
\ No newline at end of file
+        exclude_methods = ["IVtkOCC_ShapePickerAlgo::Pick", "IVtkOCC_ViewerSelector::Pick"]
